theme: jekyll-theme-slate
title : Welcome to Sharon Kang's homepage!
Description : Hi! I am a sophomore student at Mount Holyoke College. Please feel free to bookmark this page and keep an eye on my journey in Computer Science!
